# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import whereami_pb2 as protos_dot_whereami__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/whereami_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WhereamiStub(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPayload = channel.unary_unary(
                '/whereami.Whereami/GetPayload',
                request_serializer=protos_dot_whereami__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_whereami__pb2.WhereamiReply.FromString,
                _registered_method=True)


class WhereamiServicer(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    def GetPayload(self, request, context):
        """Send host name and get other metadata back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhereamiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayload,
                    request_deserializer=protos_dot_whereami__pb2.Empty.FromString,
                    response_serializer=protos_dot_whereami__pb2.WhereamiReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whereami.Whereami', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whereami.Whereami', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Whereami(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    @staticmethod
    def GetPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whereami.Whereami/GetPayload',
            protos_dot_whereami__pb2.Empty.SerializeToString,
            protos_dot_whereami__pb2.WhereamiReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
