# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/whereami.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/whereami.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/whereami.proto\x12\x08whereami\"\x07\n\x05\x45mpty\"\xd4\x02\n\rWhereamiReply\x12/\n\x0e\x62\x61\x63kend_result\x18\x01 \x01(\x0b\x32\x17.whereami.WhereamiReply\x12\x14\n\x0c\x63luster_name\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12\x11\n\tnode_name\x18\x04 \x01(\t\x12\x0e\n\x06pod_ip\x18\x05 \x01(\t\x12\x10\n\x08pod_name\x18\x06 \x01(\t\x12\x16\n\x0epod_name_emoji\x18\x07 \x01(\t\x12\x15\n\rpod_namespace\x18\x08 \x01(\t\x12\x1b\n\x13pod_service_account\x18\t \x01(\t\x12\x12\n\nproject_id\x18\n \x01(\t\x12\x11\n\ttimestamp\x18\x0b \x01(\t\x12\x0c\n\x04zone\x18\x0c \x01(\t\x12\x17\n\x0fgce_instance_id\x18\r \x01(\t\x12\x1b\n\x13gce_service_account\x18\x0e \x01(\t2D\n\x08Whereami\x12\x38\n\nGetPayload\x12\x0f.whereami.Empty\x1a\x17.whereami.WhereamiReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.whereami_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_WHEREAMIREPLY']._serialized_start=45
  _globals['_WHEREAMIREPLY']._serialized_end=385
  _globals['_WHEREAMI']._serialized_start=387
  _globals['_WHEREAMI']._serialized_end=455
# @@protoc_insertion_point(module_scope)
